# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 07:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_notes_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='user',
        ),
    ]
