# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_auto_20161205_0328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='hivepk',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
