# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 08:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_auto_20161205_0329'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteX',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hivepk', models.IntegerField(default=0)),
                ('notes_title', models.CharField(max_length=250)),
                ('notes_file', models.FileField(default='', upload_to=b'')),
                ('hive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Hive')),
            ],
        ),
        migrations.RemoveField(
            model_name='notes',
            name='hivepk',
        ),
    ]
