# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-06 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_auto_20161206_0731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notex',
            name='hive',
        ),
        migrations.AlterField(
            model_name='messageboard',
            name='message',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.DeleteModel(
            name='NoteX',
        ),
    ]
